---
DISABLE:
  - COPYPASTE
  - HTML
  - SPELL

DISABLE_LINTERS:
  - GO_REVIVE # We're running revive via golangci-lint already.

EXCLUDED_DIRECTORIES: ["testdata"]
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: 'CHANGELOG\.md'
REPOSITORY_TRIVY_ARGUMENTS: --db-repository public.ecr.aws/aquasecurity/trivy-db:2 --ignorefile .trivyignore.yaml
