DISABLE:
  - COPYPASTE
  - HTML
  - SPELL

DISABLE_LINTERS:
  - GO_REVIVE # We're running revive via golangci-lint already.

REPOSITORY_TRIVY_ARGUMENTS: --db-repository public.ecr.aws/aquasecurity/trivy-db:2 --ignorefile .trivyignore.yaml
