site_name: sops-check
site_description: |
  Tool that looks for SOPS files in a repository
  and makes sure that they are configured in the desired fashion
nav:
  - Design: design.md
  - Glossary: glossary.md
